
<nav>
    <div>
        <div>
            <div class="max-width">
                <a href="/"><i class="material-icons">home</i></a>

                <a class="grey darken-2" href="/admin/kudb/">KuDB v1.1</a>

                <a data-toggle="aside, #sidenav-overlay"><i class="material-icons">list</i></a>
                
                <a href=".."><i class="material-icons">arrow_upward</i></a>
            </div>
        </div>
    </div>
</nav>
