<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
	<head>
		<meta http-equiv="Content-type" content="text/html; charset=UTF-8" />
		<title>Pantalla <?php echo "$controller_name $action_name"; ?></title>	
		<?php Tag::css( 'style' ); ?>
		<?php Tag::css( 'fw' ); ?>
		<?php Tag::css( 'tools/tabs' ); ?>
		<?php Tag::css( 'tools/forms' ); ?>
		<?php Tag::css( 'kudb' ); ?>
		<?php echo Html::includeCss() ?>

		<?php echo Tag::js('jquery/jquery.min'); ?>
		<?php echo Tag::js('jquery/jquery.tools.min'); ?>
		<?php echo Tag::js('jquery/jquery.kumbiaphp.min'); ?>
	</head>
	<body>
		<table>
			<tr>
				<td valign="top"><?php echo View::partial( 'servidores' ); ?></td>
				<td valign="top"><?php View::content(); ?></td>
			</tr>
		</table>
	</body>
</html>

<?php echo Tag::js('kudb'); ?>
