
<ul>
	<?php
	foreach ( $_SESSION['hosts'] as $data )
	{
		$host = $data['host'];
		?>
		<li>
			<h2><?php echo $host; ?></h2>
			<?php
			$databases = Load::model( 'kudb' )->getDatabases( $host );
			?>
			<ul class="accordion">
				<?php
				foreach ( $databases as $id => $database )
				{
					?>
					<li>
						<h2><?php echo $database; ?></h2>
						<?php
						$tables = Load::model( 'kudb' )->getTables( $host, $database );
						?>
						<ul class="pane">
							<?php
							foreach ( $tables as $table )
							{
								?>
								<li><?php echo Html::link( "kudb/config/$host/$database/$table", $table ); ?></li>
								<?php
							}
							?>
						</ul>
					</li>
					<?php
				}
				?>
			</ul>
		</li>
		<?php
	}
	?>
</ul>

<?php
# BASE DE DATOS POR DEFECTO PARA EL ACORDEON
$ids = array_flip( $databases );
#_::_die_( $databases );
$database = $_SESSION['database'];
?>
<span class="accordion-default hide"><?php echo $ids[$database]; ?></span>
